build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: diffuse-eraser
python_version: py311
requirements:
  - git+https://github.com/huggingface/diffusers
  - torch==2.4.1
  - opencv-python-headless==4.10.0.84
  - accelerate==0.34.2
  - transformers==4.44.2
  - albumentations==1.4.11
  - albucore==0.0.12
  - kornia==0.7.2
  - peft==0.11.1
  - safetensors==0.4.3
  - timm==1.0.9
  - matplotlib==3.9.0
  - python-dotenv==1.0.0
  - einops
resources:
  accelerator: A10G
  cpu: '2'
  memory: 24Gi
  use_gpu: true
system_packages:
  - ffmpeg
  - libsm6
  - libxext6
secrets: {}

model_cache:
  - repo_id: stabilityai/stable-diffusion-xl-base-1.0
    allow_patterns:
      - "*.json"
      - "*.txt"
      - "text_encoder/model.fp16.safetensors"
      - "text_encoder_2/model.fp16.safetensors"
      - "unet/diffusion_pytorch_model.fp16.safetensors"
      - "vae/diffusion_pytorch_model.fp16.safetensors"