build_commands: []
environment_variables: {}
external_package_dirs: []
model_metadata: {}
model_name: diffuse-eraser
python_version: py311
requirements:
  - git+https://github.com/huggingface/diffusers
resources:
  accelerator: A10G
  cpu: '2'
  memory: 10Gi
  use_gpu: true
system_packages:
  - ffmpeg
  - libsm6
  - libxext6
secrets: {}

model_cache:
  - repo_id: stabilityai/stable-diffusion-xl-base-1.0
    allow_patterns:
      - "*.json"
      - "*.txt"
      - "text_encoder/model.fp16.safetensors"
      - "text_encoder_2/model.fp16.safetensors"
      - "unet/diffusion_pytorch_model.fp16.safetensors"
      - "vae/diffusion_pytorch_model.fp16.safetensors"